name       : arc-gtk-theme
version    : '20220223'
release    : 28
source     :
    - https://github.com/jnsh/arc-theme/archive/refs/tags/20220223.tar.gz : b9a58efc296c3036905b9f8d19518c5c815e5140dd399ad9b81cc17d319a9093
license    : GPL-3.0-or-later
summary    : Arc GTK Theme
description: |
    A flat theme with transparent elements
component  : desktop.theme
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gnome-shell
    - inkscape
    - sassc
rundeps    :
    - gtk2-engine-murrine
replaces   :
    - arc-plank-theme
setup      : |
    meson --prefix=/usr transparent \
                        -Dthemes=gtk2,gtk3,gtk4,gnome-shell,xfwm,metacity,plank \
                        -Dgnome_shell_version=41.1 \
                        -Dgnome_shell_gresource=true

    meson --prefix=/usr solid \
                        -Dthemes=gtk2,gtk3,gtk4,gnome-shell,xfwm,metacity,plank \
                        -Dgnome_shell_version=41.1 \
                        -Dgnome_shell_gresource=true \
                        -Dtransparency=false

install    : |
    %ninja_install -C transparent/
    %ninja_install -C solid/
