name       : arc-gtk-theme
version    : 20150528
release    : 4
source     :
    - https://solus-project.com/sources/arc-theme-20150528.tar.gz : 03b6ca44d5600b8a6c3f81b17f9bcd2c591c7835557ae5d5e71b98b4f007b1ae
license    : GPL-3.0
summary    : Arc GTK Theme
description: |
    Arc GTK Theme by horst3180
setup      : |
    %patch -p1 < $pkgfiles/budgie-calendar.patch
    %configure --disable-gnome-shell \
               --disable-metacity \
               --disable-unity \
               --disable-xfwm \
               --disable-xfce-notify
build      : |
install    : |
    %make_install
