name       : arc-gtk-theme
version    : '20180715'
release    : 23
source     :
    - https://github.com/NicoHood/arc-theme/archive/20180715.tar.gz : cdb315f1b85c19c1334752da22f02096be58a8086f7000d7ff92461710a9e022
license    : GPL-3.0
summary    : Arc GTK Theme
description: |
    A flat theme with transparent elements
component  : desktop.theme
builddeps  :
    - inkscape
    - optipng
    - sassc
rundeps    :
    - gtk2-engine-murrine
setup      : |
    ./autogen.sh --enable-gnome-shell \
                 --enable-metacity \
                 --disable-unity \
                 --enable-xfwm \
                 --disable-cinnamon \
                 --with-gnome=3.22 \
                 %CONFOPTS%
install    : |
    %make_install
