name       : arc-gtk-theme
version    : 20151031
release    : 10
source     :
    - https://github.com/horst3180/Arc-theme/archive/20151031.tar.gz : cbb3a08cf2a84cb844930866b0c3a53ad82c2c52d5e05421f6388fd30498f3c9
license    : GPL-3.0
summary    : Arc GTK Theme
description: |
    Arc GTK Theme by horst3180
setup      : |
    ./autogen.sh --enable-gnome-shell \
                 --disable-metacity \
                 --disable-unity \
                 --enable-xfwm \
                 --disable-xfce-notify \
                 --disable-cinnamon \
                 --with-gnome=3.18 \
                 $CONFOPTS
install    : |
    %make_install
