name       : arc-gtk-theme
version    : '20190330'
release    : 25
source     :
    - https://github.com/NicoHood/arc-theme/releases/download/20190330/arc-theme-20190330.tar.xz : 77a6c4ffd0006cab917fdef27904a5dbd931aa0089ccd30ac43a3fb03ebc3cf7
license    : GPL-3.0-or-later
summary    : Arc GTK Theme
description: |
    A flat theme with transparent elements
component  : desktop.theme
builddeps  :
    - pkgconfig(gtk+-3.0)
    - inkscape
    - optipng
    - sassc
rundeps    :
    - gtk2-engine-murrine
setup      : |
    ./autogen.sh --enable-metacity \
                 --disable-unity \
                 --enable-xfwm \
                 --disable-cinnamon \
                 --with-gnome-shell=3.32 \
                 %CONFOPTS%
install    : |
    %make_install
