name       : arc-gtk-theme
version    : '20161119'
release    : 19
source     :
    - https://github.com/horst3180/arc-theme/archive/20161119.tar.gz : a470ab33b1ad2b4ba280e61f0e1c4f8d4973ceccc84dc2db1e37fae66b5770cd
license    : GPL-3.0
summary    : Arc GTK Theme
description: |
    Arc GTK Theme by horst3180
component  : desktop.theme
rundeps    :
    - gtk2-engine-murrine
setup      : |
    ./autogen.sh --enable-gnome-shell \
                 --enable-metacity \
                 --disable-unity \
                 --enable-xfwm \
                 --disable-cinnamon \
                 --with-gnome=3.20 \
                 %CONFOPTS%
install    : |
    %make_install
