name       : arc-gtk-theme
version    : 20150711
release    : 5
source     :
    - https://solus-project.com/sources/arc-theme-20150711.tar.gz : cc36ff0ac8466256af33ca59757d135b69eb720871adbe09651b2fd7014fb2b4
license    : GPL-3.0
summary    : Arc GTK Theme
description: |
    Arc GTK Theme by horst3180
setup      : |
    %configure --disable-gnome-shell \
               --disable-metacity \
               --disable-unity \
               --disable-xfwm \
               --disable-xfce-notify
build      : |
install    : |
    %make_install
