name       : arc-gtk-theme
version    : '20220405'
release    : 29
source     :
    - https://github.com/jnsh/arc-theme/archive/refs/tags/20220405.tar.gz : 657d6cc743facba0f7f56939653b3d0ed4c55b2ce17fef0d050ed32c1aae5f1e
license    : GPL-3.0-or-later
summary    : Arc GTK Theme
description: |
    A flat theme with transparent elements
component  : desktop.theme
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gnome-shell
    - inkscape
    - sassc
rundeps    :
    - gtk2-engine-murrine
replaces   :
    - arc-plank-theme
setup      : |
    meson --prefix=/usr transparent \
                        -Dthemes=gtk2,gtk3,gtk4,gnome-shell,xfwm,metacity,plank \
                        -Dgnome_shell_version=41.4 \
                        -Dgnome_shell_gresource=true

    meson --prefix=/usr solid \
                        -Dthemes=gtk2,gtk3,gtk4,gnome-shell,xfwm,metacity,plank \
                        -Dgnome_shell_version=41.4 \
                        -Dgnome_shell_gresource=true \
                        -Dtransparency=false

install    : |
    %ninja_install -C transparent/
    %ninja_install -C solid/
