name       : arc-gtk-theme
version    : 20150528
release    : 1
source     :
    - https://solus-project.com/sources/arc-theme-20150528.tar.gz : a575aed19b7580298eed99b74294c22c9c7f8df4b7e6622a71deb252431962fd
license    : GPL-3.0
summary    : Arc GTK Theme
description: |
    Arc GTK Theme by horst3180
builddeps  :
setup      : |
    CONFIG_SHELL=/bin/bash \
    ./autogen.sh --prefix=/usr \
    		 --disable-gnome-shell \
    		 --disable-metacity \
    		 --disable-unity --disable-xfwm
build      : |
install    : |
    %make_install
