name       : arc-gtk-theme
version    : '20190917'
release    : 27
source     :
    - https://github.com/arc-design/arc-theme/releases/download/20190917/arc-theme-20190917.tar.xz : 4218e5d493adbf2bacd9d499d53849bed0226d5839b124e185f7a61323393745
license    : GPL-3.0-or-later
summary    : Arc GTK Theme
description: |
    A flat theme with transparent elements
component  : desktop.theme
builddeps  :
    - pkgconfig(gtk+-3.0)
    - inkscape
    - optipng
    - sassc
rundeps    :
    - gtk2-engine-murrine
setup      : |
    ./autogen.sh --enable-metacity \
                 --disable-unity \
                 --enable-xfwm \
                 --disable-cinnamon \
                 --with-gnome-shell=3.32 \
                 %CONFOPTS%
install    : |
    %make_install
