name       : arc-gtk-theme
version    : 20150922
release    : 9
source     :
    - https://github.com/horst3180/Arc-theme/archive/20150922.tar.gz : 4cd69ce3fd611034c4d6be88840a23e8b9d3b6c95511459e764ff24e9e512e07
license    : GPL-3.0
summary    : Arc GTK Theme
description: |
    Arc GTK Theme by horst3180
setup      : |
    ./autogen.sh --disable-gnome-shell \
                 --disable-metacity \
                 --disable-unity \
                 --disable-xfwm \
                 --disable-xfce-notify \
                 --disable-cinnamon \
                 --with-gnome=3.16 \
                 $CONFOPTS
install    : |
    %make_install
