name       : arc-gtk-theme
version    : 20160324.1
release    : 13
source     :
    - https://github.com/horst3180/arc-theme/archive/20160324.1.tar.gz : 8f8a285574fd0c46c92bc0a93183135303ca2178c4ffa52dcb40fa78c25cd0bb
license    : GPL-3.0
summary    : Arc GTK Theme
description: |
    Arc GTK Theme by horst3180
rundeps    :
    - gtk2-engine-murrine
setup      : |
    ./autogen.sh --enable-gnome-shell \
                 --disable-metacity \
                 --disable-unity \
                 --enable-xfwm \
                 --disable-xfce-notify \
                 --disable-cinnamon \
                 --with-gnome=3.18 \
                 %CONFOPTS%
install    : |
    %make_install
