name       : arc-gtk-theme
version    : '20190213'
release    : 24
source     :
    - https://github.com/NicoHood/arc-theme/archive/20190213.tar.gz : a2053796b49767bbfde8f7e8cac27fede60f4d8744797e489e1d7486404bff96
license    : GPL-3.0
summary    : Arc GTK Theme
description: |
    A flat theme with transparent elements
component  : desktop.theme
builddeps  :
    - pkgconfig(gtk+-3.0)
    - inkscape
    - optipng
    - sassc
rundeps    :
    - gtk2-engine-murrine
setup      : |
    ./autogen.sh --enable-metacity \
                 --disable-unity \
                 --enable-xfwm \
                 --disable-cinnamon \
                 --with-gnome-shell=3.28 \
                 %CONFOPTS%
install    : |
    %make_install
